version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
      - ./postgres/pgdata:/var/lib/postgresql/data
    restart: always

#  redis:
#    image: redis
#    container_name: redis
#    hostname: redis
#    restart: unless-stopped
#    volumes:
#      - ./redis/data:/data
#      - ./redis/redis.conf:/usr/local/etc/redis.conf
#    ports:
#      - 6379:6379
#    command: redis-server /usr/local/etc/redis.conf

  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: